
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientOnly from "@/components/ui/ClientOnly";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishListContext";
import { SearchProvider } from "@/context/SearchContext";
import { Slide, ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SearchProvider>
          <CartProvider>
            <WishlistProvider>
              <ClientOnly>
                <Header />
                <div className="w-full h-px bg-gray-200" />
                <ToastContainer />
                {children}
                <Footer />
              </ClientOnly>
            </WishlistProvider>
          </CartProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
